//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOrderTbRestaurant.Book_Menu {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book_Food", Namespace="http://schemas.datacontract.org/2004/07/Order_RestaurantWCF.Model")]
    [System.SerializableAttribute()]
    public partial class Book_Food : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Food_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long OrderTable_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Food_ID {
            get {
                return this.Food_IDField;
            }
            set {
                if ((this.Food_IDField.Equals(value) != true)) {
                    this.Food_IDField = value;
                    this.RaisePropertyChanged("Food_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long OrderTable_ID {
            get {
                return this.OrderTable_IDField;
            }
            set {
                if ((this.OrderTable_IDField.Equals(value) != true)) {
                    this.OrderTable_IDField = value;
                    this.RaisePropertyChanged("OrderTable_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Book_Menu.IBookMenuSV")]
    public interface IBookMenuSV {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookMenuSV/InsertMenu", ReplyAction="http://tempuri.org/IBookMenuSV/InsertMenuResponse")]
        bool InsertMenu(WebOrderTbRestaurant.Book_Menu.Book_Food bf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookMenuSV/InsertMenu", ReplyAction="http://tempuri.org/IBookMenuSV/InsertMenuResponse")]
        System.Threading.Tasks.Task<bool> InsertMenuAsync(WebOrderTbRestaurant.Book_Menu.Book_Food bf);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookMenuSVChannel : WebOrderTbRestaurant.Book_Menu.IBookMenuSV, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookMenuSVClient : System.ServiceModel.ClientBase<WebOrderTbRestaurant.Book_Menu.IBookMenuSV>, WebOrderTbRestaurant.Book_Menu.IBookMenuSV {
        
        public BookMenuSVClient() {
        }
        
        public BookMenuSVClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookMenuSVClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookMenuSVClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookMenuSVClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertMenu(WebOrderTbRestaurant.Book_Menu.Book_Food bf) {
            return base.Channel.InsertMenu(bf);
        }
        
        public System.Threading.Tasks.Task<bool> InsertMenuAsync(WebOrderTbRestaurant.Book_Menu.Book_Food bf) {
            return base.Channel.InsertMenuAsync(bf);
        }
    }
}
