//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOrderTbRestaurant.Slide {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Banner", Namespace="http://schemas.datacontract.org/2004/07/Order_RestaurantWCF.Model")]
    [System.SerializableAttribute()]
    public partial class Banner : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> Food_CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IngredientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetaTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Food_CategoryID {
            get {
                return this.Food_CategoryIDField;
            }
            set {
                if ((this.Food_CategoryIDField.Equals(value) != true)) {
                    this.Food_CategoryIDField = value;
                    this.RaisePropertyChanged("Food_CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ingredient {
            get {
                return this.IngredientField;
            }
            set {
                if ((object.ReferenceEquals(this.IngredientField, value) != true)) {
                    this.IngredientField = value;
                    this.RaisePropertyChanged("Ingredient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetaTitle {
            get {
                return this.MetaTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaTitleField, value) != true)) {
                    this.MetaTitleField = value;
                    this.RaisePropertyChanged("MetaTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Slide.ISlideSV")]
    public interface ISlideSV {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlideSV/PageListSlide", ReplyAction="http://tempuri.org/ISlideSV/PageListSlideResponse")]
        WebOrderTbRestaurant.Slide.Banner[] PageListSlide();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlideSV/PageListSlide", ReplyAction="http://tempuri.org/ISlideSV/PageListSlideResponse")]
        System.Threading.Tasks.Task<WebOrderTbRestaurant.Slide.Banner[]> PageListSlideAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlideSV/addSlide", ReplyAction="http://tempuri.org/ISlideSV/addSlideResponse")]
        bool addSlide(WebOrderTbRestaurant.Slide.Banner entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlideSV/addSlide", ReplyAction="http://tempuri.org/ISlideSV/addSlideResponse")]
        System.Threading.Tasks.Task<bool> addSlideAsync(WebOrderTbRestaurant.Slide.Banner entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlideSV/EditSlide", ReplyAction="http://tempuri.org/ISlideSV/EditSlideResponse")]
        bool EditSlide(WebOrderTbRestaurant.Slide.Banner entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlideSV/EditSlide", ReplyAction="http://tempuri.org/ISlideSV/EditSlideResponse")]
        System.Threading.Tasks.Task<bool> EditSlideAsync(WebOrderTbRestaurant.Slide.Banner entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlideSV/DeleteSlide", ReplyAction="http://tempuri.org/ISlideSV/DeleteSlideResponse")]
        bool DeleteSlide(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlideSV/DeleteSlide", ReplyAction="http://tempuri.org/ISlideSV/DeleteSlideResponse")]
        System.Threading.Tasks.Task<bool> DeleteSlideAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlideSV/Str_Metatitle", ReplyAction="http://tempuri.org/ISlideSV/Str_MetatitleResponse")]
        string Str_Metatitle(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlideSV/Str_Metatitle", ReplyAction="http://tempuri.org/ISlideSV/Str_MetatitleResponse")]
        System.Threading.Tasks.Task<string> Str_MetatitleAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlideSV/FindID", ReplyAction="http://tempuri.org/ISlideSV/FindIDResponse")]
        WebOrderTbRestaurant.Slide.Banner FindID(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlideSV/FindID", ReplyAction="http://tempuri.org/ISlideSV/FindIDResponse")]
        System.Threading.Tasks.Task<WebOrderTbRestaurant.Slide.Banner> FindIDAsync(long id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISlideSVChannel : WebOrderTbRestaurant.Slide.ISlideSV, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SlideSVClient : System.ServiceModel.ClientBase<WebOrderTbRestaurant.Slide.ISlideSV>, WebOrderTbRestaurant.Slide.ISlideSV {
        
        public SlideSVClient() {
        }
        
        public SlideSVClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SlideSVClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SlideSVClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SlideSVClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebOrderTbRestaurant.Slide.Banner[] PageListSlide() {
            return base.Channel.PageListSlide();
        }
        
        public System.Threading.Tasks.Task<WebOrderTbRestaurant.Slide.Banner[]> PageListSlideAsync() {
            return base.Channel.PageListSlideAsync();
        }
        
        public bool addSlide(WebOrderTbRestaurant.Slide.Banner entity) {
            return base.Channel.addSlide(entity);
        }
        
        public System.Threading.Tasks.Task<bool> addSlideAsync(WebOrderTbRestaurant.Slide.Banner entity) {
            return base.Channel.addSlideAsync(entity);
        }
        
        public bool EditSlide(WebOrderTbRestaurant.Slide.Banner entity) {
            return base.Channel.EditSlide(entity);
        }
        
        public System.Threading.Tasks.Task<bool> EditSlideAsync(WebOrderTbRestaurant.Slide.Banner entity) {
            return base.Channel.EditSlideAsync(entity);
        }
        
        public bool DeleteSlide(long id) {
            return base.Channel.DeleteSlide(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteSlideAsync(long id) {
            return base.Channel.DeleteSlideAsync(id);
        }
        
        public string Str_Metatitle(string str) {
            return base.Channel.Str_Metatitle(str);
        }
        
        public System.Threading.Tasks.Task<string> Str_MetatitleAsync(string str) {
            return base.Channel.Str_MetatitleAsync(str);
        }
        
        public WebOrderTbRestaurant.Slide.Banner FindID(long id) {
            return base.Channel.FindID(id);
        }
        
        public System.Threading.Tasks.Task<WebOrderTbRestaurant.Slide.Banner> FindIDAsync(long id) {
            return base.Channel.FindIDAsync(id);
        }
    }
}
